"""empty message

Revision ID: 28a833fbf59e
Revises: f002d77e5fe4
Create Date: 2024-07-08 10:06:48.662846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28a833fbf59e'
down_revision = 'f002d77e5fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projet_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_fiche_suivi_projet')
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'])
        batch_op.drop_column('projet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projet', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_fiche_suivi_projet', ['projet'], unique=True)
        batch_op.drop_column('projet_id')

    # ### end Alembic commands ###
