"""empty message

Revision ID: 3195ffdb83a6
Revises: fe2a7912466b
Create Date: 2024-07-26 14:14:09.022288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3195ffdb83a6'
down_revision = 'fe2a7912466b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titre', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_prestation_titre'), ['titre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestation_titre'))
        batch_op.drop_column('titre')

    # ### end Alembic commands ###
