"""empty message

Revision ID: 7cbf19f7634e
Revises: 28a833fbf59e
Create Date: 2024-07-10 16:35:03.537086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '7cbf19f7634e'
down_revision = '28a833fbf59e'
branch_labels = None
depends_on = None

def index_exists(connection, table_name, index_name):
    query = text("""
    SELECT COUNT(1) 
    FROM INFORMATION_SCHEMA.STATISTICS 
    WHERE table_schema = DATABASE() 
      AND table_name = '{table_name}' 
      AND index_name = '{index_name}';
    """)
    result = connection.execute(query, {'table_name':table_name, 'index_name':index_name}).scalar()
    return result > 0

def upgrade():
    connection = op.get_bind()
    connection.execute(sa.text("ALTER TABLE fiche_suivi DROP FOREIGN KEY fiche_suivi_ibfk_5"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        if index_exists(connection, 'projet', 'ix_projet_adresse'):
            batch_op.drop_index('ix_projet_adresse')
        if index_exists(connection, 'projet', 'ix_projet_nom'):
            batch_op.drop_index('ix_projet_nom')

    op.drop_table('projet')
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projet', sa.String(length=255), nullable=True))
        batch_op.alter_column('FSN',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_fiche_suivi_projet'), ['projet'], unique=True)
        batch_op.drop_column('projet_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projet_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fiche_suivi_ibfk_5', 'projet', ['projet_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_fiche_suivi_projet'))
        batch_op.alter_column('FSN',
               existing_type=sa.String(length=7),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('projet')

    op.create_table('projet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('adresse', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='projet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.create_index('ix_projet_nom', ['nom'], unique=True)
        batch_op.create_index('ix_projet_adresse', ['adresse'], unique=True)

    # ### end Alembic commands ###
