"""empty message

Revision ID: ecc78a282d03
Revises: 842d15777823
Create Date: 2024-07-24 10:11:14.080666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc78a282d03'
down_revision = '842d15777823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.alter_column('date_debut',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.alter_column('date_debut',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
