"""empty message

Revision ID: f002d77e5fe4
Revises: 733c340724d8
Create Date: 2024-07-05 10:01:40.983402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f002d77e5fe4'
down_revision = '733c340724d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ouvrage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_ouvrage', sa.String(length=45), nullable=True),
    sa.Column('code', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ouvrage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ouvrage_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ouvrage_type_ouvrage'), ['type_ouvrage'], unique=False)

    op.create_table('prestation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_prestation', sa.String(length=45), nullable=True),
    sa.Column('code', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestation_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_prestation_type_prestation'), ['type_prestation'], unique=False)

    op.create_table('societe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=True),
    sa.Column('type_societe', sa.String(length=45), nullable=True),
    sa.Column('domaine', sa.String(length=45), nullable=True),
    sa.Column('tel1', sa.String(length=45), nullable=True),
    sa.Column('tel2', sa.String(length=45), nullable=True),
    sa.Column('fax', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('societe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_societe_domaine'), ['domaine'], unique=False)
        batch_op.create_index(batch_op.f('ix_societe_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_societe_fax'), ['fax'], unique=True)
        batch_op.create_index(batch_op.f('ix_societe_nom'), ['nom'], unique=True)
        batch_op.create_index(batch_op.f('ix_societe_tel1'), ['tel1'], unique=True)
        batch_op.create_index(batch_op.f('ix_societe_tel2'), ['tel2'], unique=True)
        batch_op.create_index(batch_op.f('ix_societe_type_societe'), ['type_societe'], unique=False)

    op.create_table('personne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=True),
    sa.Column('prenom', sa.String(length=45), nullable=True),
    sa.Column('adresse', sa.String(length=45), nullable=True),
    sa.Column('tel', sa.String(length=10), nullable=True),
    sa.Column('gsm', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=45), nullable=True),
    sa.Column('societe_id', sa.Integer(), nullable=True),
    sa.Column('poste_societe', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['societe_id'], ['societe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personne_adresse'), ['adresse'], unique=True)
        batch_op.create_index(batch_op.f('ix_personne_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_personne_gsm'), ['gsm'], unique=True)
        batch_op.create_index(batch_op.f('ix_personne_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_personne_poste_societe'), ['poste_societe'], unique=False)
        batch_op.create_index(batch_op.f('ix_personne_prenom'), ['prenom'], unique=False)
        batch_op.create_index(batch_op.f('ix_personne_profession'), ['profession'], unique=False)
        batch_op.create_index(batch_op.f('ix_personne_tel'), ['tel'], unique=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('societe_id', sa.Integer(), nullable=True),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('societe_id IS NOT NULL OR personne_id IS NOT NULL', name='check_societe_personne_not_both_null'),
    sa.ForeignKeyConstraint(['personne_id'], ['personne.id'], ),
    sa.ForeignKeyConstraint(['societe_id'], ['societe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiche_suivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FSN', sa.Integer(), nullable=True),
    sa.Column('projet', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('prestation_id', sa.Integer(), nullable=True),
    sa.Column('ouvrage_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['ouvrage_id'], ['ouvrage.id'], ),
    sa.ForeignKeyConstraint(['prestation_id'], ['prestation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiche_suivi_FSN'), ['FSN'], unique=True)
        batch_op.create_index(batch_op.f('ix_fiche_suivi_adresse'), ['adresse'], unique=True)
        batch_op.create_index(batch_op.f('ix_fiche_suivi_date_debut'), ['date_debut'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiche_suivi_projet'), ['projet'], unique=True)

    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=45), nullable=True),
    sa.Column('fiche_suivi_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fiche_suivi_id'], ['fiche_suivi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devis_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_montant'), ['montant'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_numero'), ['numero'], unique=True)

    op.create_table('dossier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=45), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('fiche_suivi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fiche_suivi_id'], ['fiche_suivi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_dossier_numero'), ['numero'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('personne_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('privilege', sa.String(length=10), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=45),
               nullable=True)
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=True)
        batch_op.create_foreign_key(None, 'personne', ['personne_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.alter_column('username',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('privilege')
        batch_op.drop_column('personne_id')
        batch_op.drop_column('password')

    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_numero'))
        batch_op.drop_index(batch_op.f('ix_dossier_annee'))

    op.drop_table('dossier')
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devis_numero'))
        batch_op.drop_index(batch_op.f('ix_devis_montant'))
        batch_op.drop_index(batch_op.f('ix_devis_date'))

    op.drop_table('devis')
    with op.batch_alter_table('fiche_suivi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiche_suivi_projet'))
        batch_op.drop_index(batch_op.f('ix_fiche_suivi_date_debut'))
        batch_op.drop_index(batch_op.f('ix_fiche_suivi_adresse'))
        batch_op.drop_index(batch_op.f('ix_fiche_suivi_FSN'))

    op.drop_table('fiche_suivi')
    op.drop_table('client')
    with op.batch_alter_table('personne', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personne_tel'))
        batch_op.drop_index(batch_op.f('ix_personne_profession'))
        batch_op.drop_index(batch_op.f('ix_personne_prenom'))
        batch_op.drop_index(batch_op.f('ix_personne_poste_societe'))
        batch_op.drop_index(batch_op.f('ix_personne_nom'))
        batch_op.drop_index(batch_op.f('ix_personne_gsm'))
        batch_op.drop_index(batch_op.f('ix_personne_email'))
        batch_op.drop_index(batch_op.f('ix_personne_adresse'))

    op.drop_table('personne')
    with op.batch_alter_table('societe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_societe_type_societe'))
        batch_op.drop_index(batch_op.f('ix_societe_tel2'))
        batch_op.drop_index(batch_op.f('ix_societe_tel1'))
        batch_op.drop_index(batch_op.f('ix_societe_nom'))
        batch_op.drop_index(batch_op.f('ix_societe_fax'))
        batch_op.drop_index(batch_op.f('ix_societe_email'))
        batch_op.drop_index(batch_op.f('ix_societe_domaine'))

    op.drop_table('societe')
    with op.batch_alter_table('prestation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestation_type_prestation'))
        batch_op.drop_index(batch_op.f('ix_prestation_code'))

    op.drop_table('prestation')
    with op.batch_alter_table('ouvrage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ouvrage_type_ouvrage'))
        batch_op.drop_index(batch_op.f('ix_ouvrage_code'))

    op.drop_table('ouvrage')
    # ### end Alembic commands ###
