"""empty message

Revision ID: fe2a7912466b
Revises: ecc78a282d03
Create Date: 2024-07-26 14:01:09.701545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe2a7912466b'
down_revision = 'ecc78a282d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestation_vf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fiche_suivi_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('unite', sa.String(length=45), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('montant_ht', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.ForeignKeyConstraint(['fiche_suivi_id'], ['fiche_suivi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestation_vf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestation_vf_montant_ht'), ['montant_ht'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestation_vf_prix_unitaire'), ['prix_unitaire'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestation_vf_quantite'), ['quantite'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestation_vf_unite'), ['unite'], unique=False)

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objet', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('generalites', sa.String(length=700), nullable=True))
        batch_op.add_column(sa.Column('montant_ht', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_ttc', sa.Float(), nullable=True))
        batch_op.drop_index('ix_devis_montant')
        batch_op.create_index(batch_op.f('ix_devis_generalites'), ['generalites'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_montant_ht'), ['montant_ht'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_montant_ttc'), ['montant_ttc'], unique=False)
        batch_op.create_index(batch_op.f('ix_devis_objet'), ['objet'], unique=False)
        batch_op.drop_column('montant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant', mysql.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_devis_objet'))
        batch_op.drop_index(batch_op.f('ix_devis_montant_ttc'))
        batch_op.drop_index(batch_op.f('ix_devis_montant_ht'))
        batch_op.drop_index(batch_op.f('ix_devis_generalites'))
        batch_op.create_index('ix_devis_montant', ['montant'], unique=False)
        batch_op.drop_column('montant_ttc')
        batch_op.drop_column('montant_ht')
        batch_op.drop_column('generalites')
        batch_op.drop_column('objet')

    with op.batch_alter_table('prestation_vf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestation_vf_unite'))
        batch_op.drop_index(batch_op.f('ix_prestation_vf_quantite'))
        batch_op.drop_index(batch_op.f('ix_prestation_vf_prix_unitaire'))
        batch_op.drop_index(batch_op.f('ix_prestation_vf_montant_ht'))

    op.drop_table('prestation_vf')
    # ### end Alembic commands ###
